#!/bin/bash

# Current Working Directory
CWD=$(pwd)

#Write out current crontab
crontab -l > mycron

#Echo new cron into cron file
echo "@reboot "$CWD"/run.py" >> mycron

#Install new cron file
crontab mycron

#Remove temp file
rm mycron

echo "Success! Script will now auto-start when you plug in your Pi!"